version: "3"
services: 
  server:
    container_name: server
    restart: always
    build: ./server
    ports:
      - "8080:8080"
  client:
    container_name: client
    build: ./client
    ports: 
      - "3000:3000"
    links:
      - server